### ISSUE TITLE
Failing Build | Start Page

### ISSUE THREAD

**Issue by tu-chill** [TULiberalArts/Start#5]
I love this page. I hope we are using it instead of opening to liberalarts.temple.edu. If we are not using it, do we need to look into the build errors, or can we leave it as is?

**Comment by lidopaglia** [comment]
Hey @tu-chill thanks! We use this as the default start page in labs & classrooms. 

Thanks as well for catching the build failure. I [updated ruby](https://github.com/TULiberalArts/Start/commit/b2c6560afff680d7681b534cdf02c3165b8641d1) to 2.5 from 2.2.5 in the travis config so now the latest version of html-proofer is running without error.
